spring:
  application:
    name: TestIntern
  datasource:
    url: jdbc:postgresql://localhost:5432/intern_test
    username: postgres
    password: 1505
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect